version: '3.1'

services:
  postgres:
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: keymanager
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: key-manager
    volumes:
      - keymanager-db:/var/lib/postgresql/data

volumes:
  keymanager-db: